### ISSUE TITLE
java.lang.NoSuchMethodError: com.musicg.wave.extension.Spectrogram.getSpectrogramData()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [loisaidasam/musicg#1]
```
Tried to run the RenderSpectrogramDemo but I got an error. It seems that a 
method is missing from the class Spectrogram. 

See below for details. 

Exception in thread "main" java.lang.NoSuchMethodError: 
com.musicg.wave.extension.Spectrogram.getSpectrogramData()[[D
    at com.musicg.graphic.GraphicRender.renderSpectrogram(GraphicRender.java:138)
    at RenderSpectrogramDemo.main(RenderSpectrogramDemo.java:39)



```

Original issue reported on code.google.com by `Albert.L...@gmail.com` on 19 Sep 2012 at 3:27

**Comment by jnisperuza** [comment]
Hola a todos, comenzando un trabajo de investigacion de la universidad me encontré con este maravilloso proyecto, el cual presenta un inconveniente en su ejemplo: RenderSpectrogramDemo, el cual no genera el espectograma, después de analizar y modificar el código de la API logré solucionar el inconveniente.
[musicg-google](http://escribojava.blogspot.com.co/2017/04/musicg-google.html)
